name = "aethoria"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "aethoria"
routes = [
  { pattern = "aethoria.pages.dev/*", zone_name = "" }
]

[[analytics_engine_datasets]]
binding = "ANALYTICS"

[[r2_buckets]]
binding = "GAME_ASSETS"
bucket_name = "aethoria-assets"
